spring:
  #Activiti7配置
  activiti:
    # 自动部署验证设置:true-开启（默认）、false-关闭
    check-process-definitions: false
    #自动创建表
    #database-schema-update: drop-create
    database-schema-update: false
    #使用历史表
    history-level: full
    db-history-used: true
    # 关闭自动部署
    deployment-mode: never-fail
    #自动部署文件路径前后缀
    #process-definition-location-prefix: classpath:/bpm/
    #process-definition-location-suffixes: **.bpmn,**.bpmn20.xml